name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: powerplatform-actions
      uses: microsoft/powerplatform-actions@0.5.1

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ secrets.devenv }}
        app-id:  ${{ secrets.powerplatformsp_appid }}
        client-secret: ${{ secrets.powerplatformsp_secret }}
        tenant-id: ${{ secret.tenantid }}
    
    - name: publish-solution
      uses: microsoft/powerplatform-actions/publish-solution@v0
      with:
        solution-file: ${{ secrets.learningapp }}
        environment-url: ${{ secrets.devenv }}
        app-id:  ${{ secrets.powerplatformsp_appid }}
        client-secret: ${{ secrets.powerplatformsp_secret }}
        tenant-id: ${{ secret.tenantid }}
    
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ secrets.devenv }}
        app-id:  ${{ secrets.powerplatformsp_appid }}
        client-secret: ${{ secrets.powerplatformsp_secret }}
        tenant-id: ${{ secret.tenantid }}
        solution-name: ${{ secrets.learningapp }}
        solution-output-file: out/exported/${{ secrets.learningapp }}.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/${{ secrets.learningapp }}.zip
        solution-folder: out/solutions/${{ secrets.learningapp }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/${{ secrets.learningapp }}
        solution-target-folder: solutions/${{ secrets.learningapp }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
